version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "2000:5000"  # Map host port 2000 to container port 5000
    volumes:
      # For development - mount source code for hot reloading
      - ./frontend:/app
      # Exclude node_modules from being overwritten by the mount
      - /app/node_modules