version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Keeping your existing port mapping
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongodb:27017/predicta
      - PORT=5000
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
   # ports:
    #  - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data: